### ISSUE TITLE
Legacy Data feed is going away in January, need to update for the v3 JSON feed

### ISSUE THREAD

**Issue by mikeyusc** [skymeyer/Vatsimphp#28]
Please see https://forums.vatsim.net/blogs/entry/1-vatsim-tech-blog-q4-2020/

**Comment by skymeyer** [comment]
That's about bloody time having JSON format. Thank you for bringing this up @mikeyusc. Will look into it and see how to proceed in the best possible way.

**Comment by skymeyer** [comment]
New releases have been created using the new data feed JSON v3 API:

- https://packagist.org/packages/skymeyer/vatsimphp#2.0.1
- https://packagist.org/packages/skymeyer/vatsimphp#1.0.5

@mikeyusc let me know if you are able to test drive any of the above.

**Comment by skymeyer** [comment]
@CalumTowers ☝️ this may be of interest to you as well.

**Comment by CalumTowers** [comment]
> @CalumTowers ☝️ this may be of interest to you as well.

Nice work, thanks!
