### ISSUE TITLE
Discrepancy with reporting of times

### ISSUE THREAD

**Issue by andrewogden1678** [skymeyer/Vatsimphp#35]
Since the last update, the format of datetime has changed and is no longer the format my tool expects to use.

Let me know if you need me to paste items from discord here.

**Comment by skymeyer** [comment]
@andrewogden1678 This should be fixed. Running some final tests and I will cut a new release for both 2.x and 1.x to make the fix available.

**Comment by skymeyer** [comment]
Fixed in:
- https://github.com/skymeyer/Vatsimphp/releases/tag/2.0.2
- https://github.com/skymeyer/Vatsimphp/releases/tag/1.0.6
